name: big_fraction
description: A package that helps you working with fractions and mixed fractions. Fork that uses BigInt for numerator and denominator.
version: 5.0.1
repository: https://github.com/jimmyl0l3c/big_fraction
homepage: https://github.com/jimmyl0l3c/big_fraction

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.17.1

  # https://pub.dev/packages/test
  test: ^1.21.5
