name: big_fraction
description: A package that helps you working with fractions and mixed fractions. Fork that uses BigInt for numerator and denominator.
version: 6.0.0
repository: https://github.com/jimmyl0l3c/big_fraction
homepage: https://github.com/jimmyl0l3c/big_fraction

environment:
  sdk: ">=3.0.2 <4.0.0"

dev_dependencies:
  # https://pub.dev/packages/test
  test: ^1.24.6
